
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 02 01:15:00 KST 2016
//----------------------------------------------------

package Absyn;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LTE = 33;
  public static final int RBR = 13;
  public static final int UMINUS = 26;
  public static final int CASE = 8;
  public static final int SEMI = 37;
  public static final int INT = 20;
  public static final int LPR = 14;
  public static final int FOR = 4;
  public static final int LSQ = 16;
  public static final int LT = 31;
  public static final int COMMA = 18;
  public static final int DIV = 28;
  public static final int ASSIGN = 11;
  public static final int IF = 5;
  public static final int ID = 23;
  public static final int INT_N = 24;
  public static final int EOF = 0;
  public static final int RETURN = 22;
  public static final int RPR = 15;
  public static final int error = 1;
  public static final int MUL = 27;
  public static final int RSQ = 17;
  public static final int ADD = 29;
  public static final int NEQ = 36;
  public static final int BREAK = 10;
  public static final int EQ = 35;
  public static final int GTE = 34;
  public static final int SWITCH = 7;
  public static final int COLON = 19;
  public static final int ELSE = 6;
  public static final int WHILE = 2;
  public static final int DEFAULT = 9;
  public static final int LBR = 12;
  public static final int FLOAT = 21;
  public static final int FLOAT_N = 25;
  public static final int GT = 32;
  public static final int SUB = 30;
  public static final int DO = 3;
}

